name: push
on:
  workflow_dispatch:
  push:
  pull_request_review:

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Access private repository
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: git config --global --add safe.directory "${PWD}"
      - run: nix flake check

  generate-readme:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Access private repository
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v19
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: mkdir newreadme
      - run: (grep -B 99999 "BEGIN SERVICE LIST" README.md && nix eval --offline --raw --file bin/generateServicesTable.nix && grep -A 99999 "END SERVICE LIST" README.md) > newreadme/README.md
      - uses: actions/upload-artifact@v4
        with:
          name: new-readme
          path: newreadme

  push-readme:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - lint
      - generate-readme
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: new-readme
          path: newreadme
      - run: mv newreadme/README.md README.md
      - name: Commit and push README
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git diff-index --quiet HEAD || git commit -m "chore: Generate README.md"
          git push
