name: push
on:
  workflow_dispatch:
  push:
  pull_request_review:

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Access private repository
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - run: git config --global --add safe.directory "${PWD}"
      - run: nix flake check

  generate-readme:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Access private repository
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - run: (grep -B 99999 "BEGIN SERVICE LIST" README.md && bash bin/generateServiceTable.sh && grep -A 99999 "END SERVICE LIST" README.md) > NEW_README.md
      - run: mv NEW_README.md README.md
      - name: Commit and push README
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git diff-index --quiet HEAD || git commit -m "chore: Generate README.md"
          git push
